long_query <- "
SELECT * 
FROM
	(
	WITH ret_grad AS
		(
		SELECT
		FA01_YEAR_ENROLLED, 
	--	FA01_SEMESTER_ENROLLED_DESC,
		COL.COLLEGE_NAME_DESC,
		COL.COLLEGE_TYPE_DESC,
	--	HST.DEGREE_STATUS_DESC,
		HST.GENDER_DESC,
		HST.RESIDENCY_TYPE_DESC,
		HST.AGE_GROUP_2_DESC,
		HST.ETH_IMP_GROUP_1_DESC,
		FA01_FULL_PART_TYPE_DESC, 
		FA01_REGULAR_SPECIAL_DESC, 
		FA01_ADMISSION_TYPE_DESC, 
		FA01_NEW_STUDENT_DESC, 
		FA01_DEGREE_PURSUED_LEVEL_DESC, 

---------- INSTITUTION RATES --------------------------------------------------------------------------------------------------------------------------------------
		-- INSTITUTION *RETENTION* NUMERATOR CALCULATIONS
		sum(case when FA01_COLLEGE_ID=SP01_COLLEGE_ID -- make sure they are still at the same college as when they started
			AND SP01_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-12)) -- do not count for current academic year cohort
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_1SEM_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA02_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD01_DEGREE_EARNED_LEVEL_CODE, 0) 
			AND FA02_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-12)) -- do not count for current academic year cohort
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_1YR_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA03_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD02_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA03_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-24)) -- do not count for current or 1 past academic year
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_2YR_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA04_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD03_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA04_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-36)) -- do not count for current or 2 past academic years
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_3YR_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA05_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD04_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA05_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-48)) -- do not count for current or 3 past academic years
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_4YR_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA06_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD05_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA06_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-60)) -- etc...
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_5YR_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA07_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD06_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA07_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-72))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_6YR_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA08_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD07_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA08_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-84))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_7YR_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA09_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD08_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA09_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-96))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_8YR_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA10_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD09_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA10_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-108))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_9YR_INST_RET,
		sum(case when FA01_COLLEGE_ID=FA11_COLLEGE_ID 
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD10_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA11_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-120))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_10YR_INST_RET,

		-- INSTITUTION *GRADUATION* NUMERATOR CALCULATIONS
		sum(case when	(	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21')) -- make sure the degree earned is the same or greater than the one they pursued in their first semester AND they are still at the same college as when they started - or 21?
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-12)) -- do not count for current academic year cohort
			then FA01_HEADCOUNT ELSE NULL END) AS N_1YR_INST_GRAD,
		sum(case when	(	(CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD02_COLLEGE_ID = FA01_COLLEGE_ID) OR CD02_COLLEGE_ID = '21'))
						OR	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21'))
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-24)) -- do not count for current or 1 past academic year
			then FA01_HEADCOUNT ELSE NULL END) AS N_2YR_INST_GRAD,
			
		sum(case when	(	(CD03_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD03_COLLEGE_ID = FA01_COLLEGE_ID) OR CD03_COLLEGE_ID = '21'))
						OR	(CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD02_COLLEGE_ID = FA01_COLLEGE_ID) OR CD02_COLLEGE_ID = '21'))
						OR	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21'))
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-36)) -- do not count for current or 2 past academic years
			then FA01_HEADCOUNT ELSE NULL END) AS N_3YR_INST_GRAD,
			
		sum(case when	(	(CD04_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD04_COLLEGE_ID = FA01_COLLEGE_ID) OR CD04_COLLEGE_ID = '21'))
						OR	(CD03_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD03_COLLEGE_ID = FA01_COLLEGE_ID) OR CD03_COLLEGE_ID = '21'))
						OR	(CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD02_COLLEGE_ID = FA01_COLLEGE_ID) OR CD02_COLLEGE_ID = '21'))
						OR	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21'))
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-48)) -- do not count for current or 3 past academic years
			then FA01_HEADCOUNT ELSE NULL END) AS N_4YR_INST_GRAD,
			
		sum(case when	(	(CD05_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD05_COLLEGE_ID = FA01_COLLEGE_ID) OR CD05_COLLEGE_ID = '21'))
						OR	(CD04_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD04_COLLEGE_ID = FA01_COLLEGE_ID) OR CD04_COLLEGE_ID = '21'))
						OR	(CD03_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD03_COLLEGE_ID = FA01_COLLEGE_ID) OR CD03_COLLEGE_ID = '21'))
						OR	(CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD02_COLLEGE_ID = FA01_COLLEGE_ID) OR CD02_COLLEGE_ID = '21'))
						OR	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21'))
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-60)) -- etc...
			then FA01_HEADCOUNT ELSE NULL END) AS N_5YR_INST_GRAD,
			
		sum(case when	(	(CD06_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD06_COLLEGE_ID = FA01_COLLEGE_ID) OR CD06_COLLEGE_ID = '21'))
						OR	(CD05_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD05_COLLEGE_ID = FA01_COLLEGE_ID) OR CD05_COLLEGE_ID = '21'))
						OR	(CD04_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD04_COLLEGE_ID = FA01_COLLEGE_ID) OR CD04_COLLEGE_ID = '21'))
						OR	(CD03_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD03_COLLEGE_ID = FA01_COLLEGE_ID) OR CD03_COLLEGE_ID = '21'))
						OR	(CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD02_COLLEGE_ID = FA01_COLLEGE_ID) OR CD02_COLLEGE_ID = '21'))
						OR	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21'))
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-72))
			then FA01_HEADCOUNT ELSE NULL END) AS N_6YR_INST_GRAD,
			
		sum(case when	(	(CD07_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD07_COLLEGE_ID = FA01_COLLEGE_ID) OR CD07_COLLEGE_ID = '21'))
						OR	(CD06_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD06_COLLEGE_ID = FA01_COLLEGE_ID) OR CD06_COLLEGE_ID = '21'))
						OR	(CD05_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD05_COLLEGE_ID = FA01_COLLEGE_ID) OR CD05_COLLEGE_ID = '21'))
						OR	(CD04_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD04_COLLEGE_ID = FA01_COLLEGE_ID) OR CD04_COLLEGE_ID = '21'))
						OR	(CD03_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD03_COLLEGE_ID = FA01_COLLEGE_ID) OR CD03_COLLEGE_ID = '21'))
						OR	(CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD02_COLLEGE_ID = FA01_COLLEGE_ID) OR CD02_COLLEGE_ID = '21'))
						OR	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21'))
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-84))
			then FA01_HEADCOUNT ELSE NULL END) AS N_7YR_INST_GRAD,
			
		sum(case when	(	(CD08_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD08_COLLEGE_ID = FA01_COLLEGE_ID) OR CD08_COLLEGE_ID = '21'))
						OR	(CD07_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD07_COLLEGE_ID = FA01_COLLEGE_ID) OR CD07_COLLEGE_ID = '21'))
						OR	(CD06_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD06_COLLEGE_ID = FA01_COLLEGE_ID) OR CD06_COLLEGE_ID = '21'))
						OR	(CD05_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD05_COLLEGE_ID = FA01_COLLEGE_ID) OR CD05_COLLEGE_ID = '21'))
						OR	(CD04_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD04_COLLEGE_ID = FA01_COLLEGE_ID) OR CD04_COLLEGE_ID = '21'))
						OR	(CD03_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD03_COLLEGE_ID = FA01_COLLEGE_ID) OR CD03_COLLEGE_ID = '21'))
						OR	(CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD02_COLLEGE_ID = FA01_COLLEGE_ID) OR CD02_COLLEGE_ID = '21'))
						OR	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21'))
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-96))
			then FA01_HEADCOUNT ELSE NULL END) AS N_8YR_INST_GRAD,
			
		sum(case when	(	(CD09_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD09_COLLEGE_ID = FA01_COLLEGE_ID) OR CD09_COLLEGE_ID = '21'))
						OR	(CD08_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD08_COLLEGE_ID = FA01_COLLEGE_ID) OR CD08_COLLEGE_ID = '21'))
						OR	(CD07_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD07_COLLEGE_ID = FA01_COLLEGE_ID) OR CD07_COLLEGE_ID = '21'))
						OR	(CD06_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD06_COLLEGE_ID = FA01_COLLEGE_ID) OR CD06_COLLEGE_ID = '21'))
						OR	(CD05_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD05_COLLEGE_ID = FA01_COLLEGE_ID) OR CD05_COLLEGE_ID = '21'))
						OR	(CD04_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD04_COLLEGE_ID = FA01_COLLEGE_ID) OR CD04_COLLEGE_ID = '21'))
						OR	(CD03_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD03_COLLEGE_ID = FA01_COLLEGE_ID) OR CD03_COLLEGE_ID = '21'))
						OR	(CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD02_COLLEGE_ID = FA01_COLLEGE_ID) OR CD02_COLLEGE_ID = '21'))
						OR	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21'))
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-108))
			then FA01_HEADCOUNT ELSE NULL END) AS N_9YR_INST_GRAD,
			
		sum(case when	(	(CD10_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD10_COLLEGE_ID = FA01_COLLEGE_ID) OR CD10_COLLEGE_ID = '21'))
						OR	(CD09_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD09_COLLEGE_ID = FA01_COLLEGE_ID) OR CD09_COLLEGE_ID = '21'))
						OR	(CD08_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD08_COLLEGE_ID = FA01_COLLEGE_ID) OR CD08_COLLEGE_ID = '21'))
						OR	(CD07_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD07_COLLEGE_ID = FA01_COLLEGE_ID) OR CD07_COLLEGE_ID = '21'))
						OR	(CD06_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD06_COLLEGE_ID = FA01_COLLEGE_ID) OR CD06_COLLEGE_ID = '21'))
						OR	(CD05_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD05_COLLEGE_ID = FA01_COLLEGE_ID) OR CD05_COLLEGE_ID = '21'))
						OR	(CD04_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD04_COLLEGE_ID = FA01_COLLEGE_ID) OR CD04_COLLEGE_ID = '21'))
						OR	(CD03_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD03_COLLEGE_ID = FA01_COLLEGE_ID) OR CD03_COLLEGE_ID = '21'))
						OR	(CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD02_COLLEGE_ID = FA01_COLLEGE_ID) OR CD02_COLLEGE_ID = '21'))
						OR	(CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE AND ((CD01_COLLEGE_ID = FA01_COLLEGE_ID) OR CD01_COLLEGE_ID = '21'))
						)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-120))
			then FA01_HEADCOUNT ELSE NULL END) AS N_10YR_INST_GRAD,

---------- SYSTEM RATES -------------------------------------------------------------------------------------------------------------------------------------------
		-- SYSTEM *RETENTION* NUMERATOR CALCULATIONS
		sum(case when SP01_COLLEGE_ID IS NOT NULL -- make sure they are still at the same college as when they started
			AND SP01_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-12)) -- do not count for current academic year cohort
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_1SEM_SYS_RET,
		sum(case when FA02_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD01_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA02_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-12)) -- do not count for current academic year cohort
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_1YR_SYS_RET,
		sum(case when FA03_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD02_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA03_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-24)) -- do not count for current or 1 past academic year
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_2YR_SYS_RET,
		sum(case when FA04_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD03_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA04_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-36)) -- do not count for current or 2 past academic years
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_3YR_SYS_RET,
		sum(case when FA05_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD04_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA05_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-48)) -- do not count for current or 3 past academic years
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_4YR_SYS_RET,
		sum(case when FA06_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD05_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA06_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-60)) -- etc...
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_5YR_SYS_RET,
		sum(case when FA07_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD06_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA07_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-72))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_6YR_SYS_RET,
		sum(case when FA08_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD07_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA08_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-84))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_7YR_SYS_RET,
		sum(case when FA09_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD08_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA09_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-96))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_8YR_SYS_RET,
		sum(case when FA10_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD09_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA10_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-108))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_9YR_SYS_RET,
		sum(case when FA11_COLLEGE_ID IS NOT NULL
			AND FA01_DEGREE_PURSUED_LEVEL_CODE > NVL(CD10_DEGREE_EARNED_LEVEL_CODE, 0)
			AND FA11_DEGREE_PURSUED_LEVEL_CODE <> '9'
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-120))
			THEN FA01_HEADCOUNT ELSE NULL END) AS N_10YR_SYS_RET,

		-- SYSTEM *GRADUATION* NUMERATOR CALCULATIONS
		sum(case when (CD01_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-12))
			then FA01_HEADCOUNT ELSE NULL END) AS N_1YR_SYS_GRAD,
		sum(case when (CD02_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-24))
			then FA01_HEADCOUNT ELSE NULL END) AS N_2YR_SYS_GRAD,
		sum(case when (CD03_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-36))
			then FA01_HEADCOUNT ELSE NULL END) AS N_3YR_SYS_GRAD,
		sum(case when (CD04_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-48))
			then FA01_HEADCOUNT ELSE NULL END) AS N_4YR_SYS_GRAD,
		sum(case when (CD05_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-60))
			then FA01_HEADCOUNT ELSE NULL END) AS N_5YR_SYS_GRAD,
		sum(case when (CD06_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-72))
			then FA01_HEADCOUNT ELSE NULL END) AS N_6YR_SYS_GRAD,
		sum(case when (CD07_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-84))
			then FA01_HEADCOUNT ELSE NULL END) AS N_7YR_SYS_GRAD,
		sum(case when (CD08_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-96))
			then FA01_HEADCOUNT ELSE NULL END) AS N_8YR_SYS_GRAD,
		sum(case when (CD09_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-108))
			then FA01_HEADCOUNT ELSE NULL END) AS N_9YR_SYS_GRAD,
		sum(case when (CD10_DEGREE_EARNED_LEVEL_CODE >= FA01_DEGREE_PURSUED_LEVEL_CODE)
			AND FA01_YEAR_ENROLLED < EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-120))
			then FA01_HEADCOUNT ELSE NULL END) AS N_10YR_SYS_GRAD,

		SUM(FA01_HEADCOUNT) AS DENOMINATOR

		FROM
		IR.HISTORY_FACTS HST

		LEFT OUTER JOIN
		IR.COLLEGE_LOOKUP COL
		ON HST.COLLEGE_ID=COL.COLLEGE_ID

		LEFT OUTER JOIN
		IR.COHORT_FACTS COH
		ON HST.STUDENT_ID=FA01_STUDENT_ID
		AND HST.COLLEGE_ID=FA01_COLLEGE_ID
		AND HST.TERM_ENROLLED_DATE=FA01_TERM_ENROLLED_DATE

		WHERE
		FA01_YEAR_ENROLLED >= EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-192)) 
		AND FA01_YEAR_ENROLLED <= EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-24))
		-- AND FA01_NEW_STUDENT_CODE = '1'
		-- AND FA01_FULL_PART_TYPE_CODE = '1'
		AND FA01_DEGREE_PURSUED_LEVEL_CODE IN ('2', '3')

		GROUP BY
		FA01_YEAR_ENROLLED, 
	--	FA01_SEMESTER_ENROLLED_DESC,
		COL.COLLEGE_NAME_DESC,
		COL.COLLEGE_TYPE_DESC,
	--	HST.DEGREE_STATUS_DESC,
		HST.GENDER_DESC,
		HST.RESIDENCY_TYPE_DESC,
		HST.AGE_GROUP_2_DESC,
		HST.ETH_IMP_GROUP_1_DESC,
		FA01_FULL_PART_TYPE_DESC, 
		FA01_REGULAR_SPECIAL_DESC, 
		FA01_ADMISSION_TYPE_DESC, 
		FA01_NEW_STUDENT_DESC, 
		FA01_DEGREE_PURSUED_LEVEL_DESC

		ORDER BY
		FA01_YEAR_ENROLLED, 
	--	FA01_SEMESTER_ENROLLED_DESC,
		COL.COLLEGE_NAME_DESC,
		COL.COLLEGE_TYPE_DESC,
	--	HST.DEGREE_STATUS_DESC,
		HST.GENDER_DESC,
		HST.RESIDENCY_TYPE_DESC,
		HST.AGE_GROUP_2_DESC,
		HST.ETH_IMP_GROUP_1_DESC,
		FA01_FULL_PART_TYPE_DESC, 
		FA01_REGULAR_SPECIAL_DESC, 
		FA01_ADMISSION_TYPE_DESC, 
		FA01_NEW_STUDENT_DESC, 
		FA01_DEGREE_PURSUED_LEVEL_DESC
		)

	SELECT ret_grad.*,
		CASE WHEN (N_1YR_INST_RET IS NULL AND N_1YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_1YR_INST_RET,0) + NVL(N_1YR_INST_GRAD,0)) END AS N_1YR_INST_PERS, 
		CASE WHEN (N_2YR_INST_RET IS NULL AND N_2YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_2YR_INST_RET,0) + NVL(N_2YR_INST_GRAD,0)) END AS N_2YR_INST_PERS,
		CASE WHEN (N_3YR_INST_RET IS NULL AND N_3YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_3YR_INST_RET,0) + NVL(N_3YR_INST_GRAD,0)) END AS N_3YR_INST_PERS,
		CASE WHEN (N_4YR_INST_RET IS NULL AND N_4YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_4YR_INST_RET,0) + NVL(N_4YR_INST_GRAD,0)) END AS N_4YR_INST_PERS,
		CASE WHEN (N_5YR_INST_RET IS NULL AND N_5YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_5YR_INST_RET,0) + NVL(N_5YR_INST_GRAD,0)) END AS N_5YR_INST_PERS,
		CASE WHEN (N_6YR_INST_RET IS NULL AND N_6YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_6YR_INST_RET,0) + NVL(N_6YR_INST_GRAD,0)) END AS N_6YR_INST_PERS,
		CASE WHEN (N_7YR_INST_RET IS NULL AND N_7YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_7YR_INST_RET,0) + NVL(N_7YR_INST_GRAD,0)) END AS N_7YR_INST_PERS,
		CASE WHEN (N_8YR_INST_RET IS NULL AND N_8YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_8YR_INST_RET,0) + NVL(N_8YR_INST_GRAD,0)) END AS N_8YR_INST_PERS,
		CASE WHEN (N_9YR_INST_RET IS NULL AND N_9YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_9YR_INST_RET,0) + NVL(N_9YR_INST_GRAD,0)) END AS N_9YR_INST_PERS,
		CASE WHEN (N_10YR_INST_RET IS NULL AND N_10YR_INST_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_10YR_INST_RET,0) + NVL(N_10YR_INST_GRAD,0)) END AS N_10YR_INST_PERS,
		
		CASE WHEN (N_1YR_SYS_RET IS NULL AND N_1YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_1YR_SYS_RET,0) + NVL(N_1YR_SYS_GRAD,0)) END AS N_1YR_SYS_PERS,
		CASE WHEN (N_2YR_SYS_RET IS NULL AND N_2YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_2YR_SYS_RET,0) + NVL(N_2YR_SYS_GRAD,0)) END AS N_2YR_SYS_PERS,
		CASE WHEN (N_3YR_SYS_RET IS NULL AND N_3YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_3YR_SYS_RET,0) + NVL(N_3YR_SYS_GRAD,0)) END AS N_3YR_SYS_PERS,
		CASE WHEN (N_4YR_SYS_RET IS NULL AND N_4YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_4YR_SYS_RET,0) + NVL(N_4YR_SYS_GRAD,0)) END AS N_4YR_SYS_PERS,
		CASE WHEN (N_5YR_SYS_RET IS NULL AND N_5YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_5YR_SYS_RET,0) + NVL(N_5YR_SYS_GRAD,0)) END AS N_5YR_SYS_PERS,
		CASE WHEN (N_6YR_SYS_RET IS NULL AND N_6YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_6YR_SYS_RET,0) + NVL(N_6YR_SYS_GRAD,0)) END AS N_6YR_SYS_PERS,
		CASE WHEN (N_7YR_SYS_RET IS NULL AND N_7YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_7YR_SYS_RET,0) + NVL(N_7YR_SYS_GRAD,0)) END AS N_7YR_SYS_PERS,
		CASE WHEN (N_8YR_SYS_RET IS NULL AND N_8YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_8YR_SYS_RET,0) + NVL(N_8YR_SYS_GRAD,0)) END AS N_8YR_SYS_PERS,
		CASE WHEN (N_9YR_SYS_RET IS NULL AND N_9YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_9YR_SYS_RET,0) + NVL(N_9YR_SYS_GRAD,0)) END AS N_9YR_SYS_PERS,
		CASE WHEN (N_10YR_SYS_RET IS NULL AND N_10YR_SYS_GRAD IS NULL) THEN NULL ELSE
			(NVL(N_10YR_SYS_RET,0) + NVL(N_10YR_SYS_GRAD,0)) END AS N_10YR_SYS_PERS
		
	FROM ret_grad
	)

UNPIVOT (
	(Numerator, Denominator)
	FOR (Timeframe, Ret_Grad, Inst_Syst)
	IN(
	(N_1SEM_INST_RET, DENOMINATOR) as ('1 Semester', 'Retention', 'Institution'),
	(N_1YR_INST_RET, DENOMINATOR) as ('1 Year', 'Retention', 'Institution'),
	(N_1YR_INST_GRAD, DENOMINATOR) as ('1 Year', 'Graduation', 'Institution'),
	(N_1YR_INST_PERS, DENOMINATOR) as ('1 Year', 'Persistence', 'Institution'),
	(N_2YR_INST_RET, DENOMINATOR) as ('2 Year', 'Retention', 'Institution'),
	(N_2YR_INST_GRAD, DENOMINATOR) as ('2 Year', 'Graduation', 'Institution'),
	(N_2YR_INST_PERS, DENOMINATOR) as ('2 Year', 'Persistence', 'Institution'),
	(N_3YR_INST_RET, DENOMINATOR) as ('3 Year', 'Retention', 'Institution'),
	(N_3YR_INST_GRAD, DENOMINATOR) as ('3 Year', 'Graduation', 'Institution'),
	(N_3YR_INST_PERS, DENOMINATOR) as ('3 Year', 'Persistence', 'Institution'),
	(N_4YR_INST_RET, DENOMINATOR) as ('4 Year', 'Retention', 'Institution'),
	(N_4YR_INST_GRAD, DENOMINATOR) as ('4 Year', 'Graduation', 'Institution'),
	(N_4YR_INST_PERS, DENOMINATOR) as ('4 Year', 'Persistence', 'Institution'),
	(N_5YR_INST_RET, DENOMINATOR) as ('5 Year', 'Retention', 'Institution'),
	(N_5YR_INST_GRAD, DENOMINATOR) as ('5 Year', 'Graduation', 'Institution'),
	(N_5YR_INST_PERS, DENOMINATOR) as ('5 Year', 'Persistence', 'Institution'),
	(N_6YR_INST_RET, DENOMINATOR) as ('6 Year', 'Retention', 'Institution'),
	(N_6YR_INST_GRAD, DENOMINATOR) as ('6 Year', 'Graduation', 'Institution'),
	(N_6YR_INST_PERS, DENOMINATOR) as ('6 Year', 'Persistence', 'Institution'),
	(N_7YR_INST_RET, DENOMINATOR) as ('7 Year', 'Retention', 'Institution'),
	(N_7YR_INST_GRAD, DENOMINATOR) as ('7 Year', 'Graduation', 'Institution'),
	(N_7YR_INST_PERS, DENOMINATOR) as ('7 Year', 'Persistence', 'Institution'),
	(N_8YR_INST_RET, DENOMINATOR) as ('8 Year', 'Retention', 'Institution'),
	(N_8YR_INST_GRAD, DENOMINATOR) as ('8 Year', 'Graduation', 'Institution'),
	(N_8YR_INST_PERS, DENOMINATOR) as ('8 Year', 'Persistence', 'Institution'),
	(N_9YR_INST_RET, DENOMINATOR) as ('9 Year', 'Retention', 'Institution'),
	(N_9YR_INST_GRAD, DENOMINATOR) as ('9 Year', 'Graduation', 'Institution'),
	(N_9YR_INST_PERS, DENOMINATOR) as ('9 Year', 'Persistence', 'Institution'),
	(N_10YR_INST_RET, DENOMINATOR) as ('10 Year', 'Retention', 'Institution'),
	(N_10YR_INST_GRAD, DENOMINATOR) as ('10 Year', 'Graduation', 'Institution'),
	(N_10YR_INST_PERS, DENOMINATOR) as ('10 Year', 'Persistence', 'Institution'),
	
	(N_1SEM_SYS_RET, DENOMINATOR) as ('1 Semester', 'Retention', 'System'),
	(N_1YR_SYS_RET, DENOMINATOR) as ('1 Year', 'Retention', 'System'),
	(N_1YR_SYS_GRAD, DENOMINATOR) as ('1 Year', 'Graduation', 'System'),
	(N_1YR_SYS_PERS, DENOMINATOR) as ('1 Year', 'Persistence', 'System'),
	(N_2YR_SYS_RET, DENOMINATOR) as ('2 Year', 'Retention', 'System'),
	(N_2YR_SYS_GRAD, DENOMINATOR) as ('2 Year', 'Graduation', 'System'),
	(N_2YR_SYS_PERS, DENOMINATOR) as ('2 Year', 'Persistence', 'System'),
	(N_3YR_SYS_RET, DENOMINATOR) as ('3 Year', 'Retention', 'System'),
	(N_3YR_SYS_GRAD, DENOMINATOR) as ('3 Year', 'Graduation', 'System'),
	(N_3YR_SYS_PERS, DENOMINATOR) as ('3 Year', 'Persistence', 'System'),
	(N_4YR_SYS_RET, DENOMINATOR) as ('4 Year', 'Retention', 'System'),
	(N_4YR_SYS_GRAD, DENOMINATOR) as ('4 Year', 'Graduation', 'System'),
	(N_4YR_SYS_PERS, DENOMINATOR) as ('4 Year', 'Persistence', 'System'),
	(N_5YR_SYS_RET, DENOMINATOR) as ('5 Year', 'Retention', 'System'),
	(N_5YR_SYS_GRAD, DENOMINATOR) as ('5 Year', 'Graduation', 'System'),
	(N_5YR_SYS_PERS, DENOMINATOR) as ('5 Year', 'Persistence', 'System'),
	(N_6YR_SYS_RET, DENOMINATOR) as ('6 Year', 'Retention', 'System'),
	(N_6YR_SYS_GRAD, DENOMINATOR) as ('6 Year', 'Graduation', 'System'),
	(N_6YR_SYS_PERS, DENOMINATOR) as ('6 Year', 'Persistence', 'System'),
	(N_7YR_SYS_RET, DENOMINATOR) as ('7 Year', 'Retention', 'System'),
	(N_7YR_SYS_GRAD, DENOMINATOR) as ('7 Year', 'Graduation', 'System'),
	(N_7YR_SYS_PERS, DENOMINATOR) as ('7 Year', 'Persistence', 'System'),
	(N_8YR_SYS_RET, DENOMINATOR) as ('8 Year', 'Retention', 'System'),
	(N_8YR_SYS_GRAD, DENOMINATOR) as ('8 Year', 'Graduation', 'System'),
	(N_8YR_SYS_PERS, DENOMINATOR) as ('8 Year', 'Persistence', 'System'),
	(N_9YR_SYS_RET, DENOMINATOR) as ('9 Year', 'Retention', 'System'),
	(N_9YR_SYS_GRAD, DENOMINATOR) as ('9 Year', 'Graduation', 'System'),
	(N_9YR_SYS_PERS, DENOMINATOR) as ('9 Year', 'Persistence', 'System'),
	(N_10YR_SYS_RET, DENOMINATOR) as ('10 Year', 'Retention', 'System'),
	(N_10YR_SYS_GRAD, DENOMINATOR) as ('10 Year', 'Graduation', 'System'),
	(N_10YR_SYS_PERS, DENOMINATOR) as ('10 Year', 'Persistence', 'System')
	)
)
"