SELECT
HST.YEAR_ENROLLED,
HST.SEMESTER_ENROLLED_DESC,
COL.COLLEGE_NAME_CODE,
COL.COLLEGE_NAME_DESC,
COL.COLLEGE_TYPE_DESC,
HST.CLASS_LEVEL_DESC,
HST.DEGREE_STATUS_DESC,
HST.GENDER_DESC,
HST.FULL_PART_TYPE_DESC,
HST.DEGREE_PURSUED_LEVEL_DESC,
HST.RESIDENCY_TYPE_DESC,
HST.AGE_GROUP_2_DESC,
HST.ETH_IMP_GROUP_1_DESC,
NVL(HST.NEW_STUDENT_DESC, 'Continuing Students') AS NEW_STUDENT_DESC,
SUM(HST.FTE_SEM_UNDERGRAD_LEVEL_SHOW) AS UNDERGRAD_FTE,
SUM(HST.FTE_SEM_GRADUATE_LEVEL_SHOW) AS GRAD_FTE,
SUM(HST.FTE_SEM_TOTAL_SHOW) AS TOTAL_FTE,
SUM(HST.HEADCOUNT)
 
FROM
IR.HISTORY_FACTS HST

LEFT OUTER JOIN
IR.COLLEGE_LOOKUP COL
ON HST.COLLEGE_ID=COL.COLLEGE_ID

WHERE
HST.YEAR_ENROLLED <= TO_CHAR(EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-12)))

GROUP BY
HST.YEAR_ENROLLED ,
HST.SEMESTER_ENROLLED_DESC,
COL.COLLEGE_NAME_CODE,
COL.COLLEGE_NAME_DESC,
COL.COLLEGE_TYPE_DESC,
HST.CLASS_LEVEL_DESC,
HST.DEGREE_STATUS_DESC,
HST.GENDER_DESC,
HST.FULL_PART_TYPE_DESC,
HST.DEGREE_PURSUED_LEVEL_DESC,
HST.RESIDENCY_TYPE_DESC,
HST.AGE_GROUP_2_DESC,
HST.ETH_IMP_GROUP_1_DESC,
HST.NEW_STUDENT_DESC

ORDER BY
HST.YEAR_ENROLLED,
HST.SEMESTER_ENROLLED_DESC,
COL.COLLEGE_NAME_CODE,
COL.COLLEGE_NAME_DESC,
COL.COLLEGE_TYPE_DESC,
HST.CLASS_LEVEL_DESC,
HST.DEGREE_STATUS_DESC,
HST.GENDER_DESC,
HST.FULL_PART_TYPE_DESC,
HST.DEGREE_PURSUED_LEVEL_DESC,
HST.RESIDENCY_TYPE_DESC,
HST.AGE_GROUP_2_DESC,
HST.ETH_IMP_GROUP_1_DESC,
HST.NEW_STUDENT_DESC
;
